main:
  - name: Who Is Behind VyV?
    url: /about/
    weight: 5
  - name: Activities
    url: /#activities
    weight: 10
  - name: How It Works
    url: /#how-it-works
    weight: 20
  - name: FAQ
    url: /#faq
    weight: 30

footer:
  - name: Navigate
    weight: 10
  - parent: Navigate
    name: Who Is Behind VyV?
    url: /about/
    weight: 5
  - parent: Navigate
    name: Activities
    url: /#activities
    weight: 10
  - parent: Navigate
    name: How It Works
    url: /#how-it-works
    weight: 20
  - parent: Navigate
    name: FAQ
    url: /#faq
    weight: 30
  - parent: Navigate
    name: Connect
    url: /#connect
    weight: 40

  - name: Legal
    weight: 20
  - parent: Legal
    name: Privacy Policy
    url: /privacy/
    weight: 10
  - parent: Legal
    name: Terms of Service
    url: /terms/
    weight: 20
